server:
  port: 8080
#  servlet:
#    context-path: /boot
  tomcat:
    uri-encoding: utf-8

logging:
  path: logs/
  level.root: info

spring:
  datasource:
    name: root
    url: jdbc:mysql://localhost:3306/young?useSSL=false
    username: root
    password: 1234567890
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#################redis基础配置#################
  redis:
    host: 39.108.184.27
    port: 6379
    password: Guest@Redis@001
    database: 0
    timeout: 3000
    #################redis线程池设置#################
    jedis:
      pool:
        max-idle: 10
        min-idle: 1
        max-active: 10
        max-wait: 1000


mybatis:
  mapper-locations: classpath:top/oyoung/springbootdemo/mapper/*.xml

management.endpoints.web.exposure.include: info, health,env





